FROM eclipse-temurin:23-jdk

WORKDIR /app

COPY . .

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

EXPOSE 10000

CMD ["sh", "-c", "java -jar target/carbontracker-0.0.1-SNAPSHOT.jar --server.port=${PORT:-10000}"]
