spring.config.import=optional:file:./.env[.properties]

spring.application.name=carbontracker
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:4173,https://carbon-tracker-ruddy.vercel.app}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:4173}

# =========================================================
# PostgreSQL Database Configuration - Neon
# =========================================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / Hibernate
# =========================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# =========================================================
# Server
# =========================================================
server.port=${PORT:8080}

# =========================================================
# Gmail SMTP
# =========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =========================================================
# Gemini API Configuration
# =========================================================
groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.3-70b-versatile

# =========================================================
# Google OAuth2
# =========================================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${OAUTH_REDIRECT_URI:https://carbon-tracker-backend-bwec.onrender.com/login/oauth2/code/google}
spring.security.oauth2.client.provider.google.user-name-attribute=sub
